// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkJ0NuqI_7NfzHQlwTqAyNNBe-jG8Gblg',
    appId: '1:525223929092:web:a60dd19bde19b9fcefdc51',
    messagingSenderId: '525223929092',
    projectId: 'fir-6e432',
    authDomain: 'fir-6e432.firebaseapp.com',
    storageBucket: 'fir-6e432.appspot.com',
    measurementId: 'G-SM4WNW9G6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLKhe1weVtRf6OT9qdlzpt6WwdOGohfdA',
    appId: '1:525223929092:android:236d9217975e2ad8efdc51',
    messagingSenderId: '525223929092',
    projectId: 'fir-6e432',
    storageBucket: 'fir-6e432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCipU9xq4rz1jnC_egpPWPdu8oBXG330',
    appId: '1:525223929092:ios:85d40b3accd27bb6efdc51',
    messagingSenderId: '525223929092',
    projectId: 'fir-6e432',
    storageBucket: 'fir-6e432.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCipU9xq4rz1jnC_egpPWPdu8oBXG330',
    appId: '1:525223929092:ios:1549e14d63d0cb57efdc51',
    messagingSenderId: '525223929092',
    projectId: 'fir-6e432',
    storageBucket: 'fir-6e432.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
